// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsFq8rbGC6ZJjDdFNkM6h1SK1HITaJ7LA',
    appId: '1:205056297503:web:fb3851e7db6d257df0e32a',
    messagingSenderId: '205056297503',
    projectId: 'briluxforgev1',
    authDomain: 'briluxforgev1.firebaseapp.com',
    storageBucket: 'briluxforgev1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqXztrzfLsWOE-HsIhkTuGtNtr7z6S-FU',
    appId: '1:205056297503:android:33c5a45e1b415125f0e32a',
    messagingSenderId: '205056297503',
    projectId: 'briluxforgev1',
    storageBucket: 'briluxforgev1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-PBj6BHyfhtoWoa5tXeOMptI0ywutBlw',
    appId: '1:205056297503:ios:45de549a1bb01b42f0e32a',
    messagingSenderId: '205056297503',
    projectId: 'briluxforgev1',
    storageBucket: 'briluxforgev1.firebasestorage.app',
    iosBundleId: 'com.example.briluxforge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-PBj6BHyfhtoWoa5tXeOMptI0ywutBlw',
    appId: '1:205056297503:ios:45de549a1bb01b42f0e32a',
    messagingSenderId: '205056297503',
    projectId: 'briluxforgev1',
    storageBucket: 'briluxforgev1.firebasestorage.app',
    iosBundleId: 'com.example.briluxforge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsFq8rbGC6ZJjDdFNkM6h1SK1HITaJ7LA',
    appId: '1:205056297503:web:74a59ce61b5f1228f0e32a',
    messagingSenderId: '205056297503',
    projectId: 'briluxforgev1',
    authDomain: 'briluxforgev1.firebaseapp.com',
    storageBucket: 'briluxforgev1.firebasestorage.app',
  );
}
